# Generated by Django 6.1 on 2026-08-16 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='student_name',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.student'),
            preserve_default=False,
        ),
    ]
