# Generated by Django 6.1 on 2026-08-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_enrollment_student_name_enrollment_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
